"""add kyc submission fields to vendor profile

Revision ID: e2b28228dd70
Revises: fea0f31a3b8b
Create Date: 2026-08-29 21:06:36.063164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b28228dd70'
down_revision: Union[str, Sequence[str], None] = 'fea0f31a3b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_profiles', sa.Column('kyc_document_type', sa.String(length=50), nullable=True))
    op.add_column('vendor_profiles', sa.Column('kyc_document_reference', sa.String(length=255), nullable=True))
    op.add_column('vendor_profiles', sa.Column('kyc_submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_profiles', 'kyc_submitted_at')
    op.drop_column('vendor_profiles', 'kyc_document_reference')
    op.drop_column('vendor_profiles', 'kyc_document_type')
    # ### end Alembic commands ###
